/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class DayOneTest {
    @Test fun testEx1() {
        val input = "(())"
        val solver = DayOne(input)
        assertEquals(0, solver.partOne(), "solves day one correctly")
    }
}
