/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

import kotlin.test.Test
import kotlin.test.assertNotNull

class DayOneTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = DayOne()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
