/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc.`2020`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class DayOne2020Test {
    @Test fun testEx1() {
        val input = """
            1721
            979
            366
            299
            675
            1456
            """.trimIndent()
        val solver = DayOne2020(input)
        assertEquals(514579, solver.partOne(), "solves day one correctly")
    }
}
