/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc.`2020`

import kotlin.test.Test
import kotlin.test.assertEquals

class DayOne2020Test {
    private val input = """
            1721
            979
            366
            299
            675
            1456
            """.trimIndent()

    @Test fun testEx1() {
        val solver = DayOne2020(input)
        assertEquals(514579, solver.partOne(), "solves part one day one correctly")
    }

    @Test fun textEx2() {
        val solver = DayOne2020(input)
        assertEquals(241861950, solver.partTwo(), "solves part two day one correctly")
    }
}
